bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
extraFiles:
    - google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
branches:
    - branch: 1.22.0-sp
      releaseType: java-lts
    - branch: java7
    - branch: 2.2.x
      releaseType: java-backport
    - branch: v2.6.x
      releaseType: java-backport
    - branch: 2.16.x
      releaseType: java-backport
    - branch: 2.23.x
      releaseType: java-backport
    - branch: 2.25.x
      releaseType: java-backport
    - branch: 2.30.x
      releaseType: java-backport
    - branch: 2.39.x
      releaseType: java-backport
    - branch: 2.54.x
      releaseType: java-backport
    - branch: 2.61.x
      releaseType: java-backport
    - branch: 2.60.x
      releaseType: java-backport
    - branch: protobuf-4.x-rc
      manifest: true
