bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 1.22.0-sp
extraFiles:
  - google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java