bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 1.22.0-sp
    extraFiles:
      - >-
        google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    extraFiles:
      - >-
        google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    extraFiles:
      - >-
        google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
    branch: 2.2.x
extraFiles:
  - google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/Version.java
