integration_append: |
  env_vars: {
    key: "INTEGRATION_TEST_ARGS"
    value: "-P bigtable-emulator-it,bigtable-prod-it,bigtable-prod-batch-it -Dbigtable.project=gcloud-devel -Dbigtable.instance=google-cloud-bigtable -Dbigtable.table=integration-tests -Dbigtable.kms_key_name=projects/gcloud-devel/locations/us-east1/keyRings/cmek-test-key-ring/cryptoKeys/cmek-test-key -Dbigtable.wait-for-cmek-key-status=true"
  }

  env_vars: {
    key: "GCLOUD_PROJECT"
    value: "gcloud-devel"
  }
  
  env_vars: {
    key: "GOOGLE_CLOUD_PROJECT"
    value: "gcloud-devel"
  }