// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_table_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface CheckConsistencyResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.CheckConsistencyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * True only if the token is consistent. A token is consistent if replication
   * has caught up with the restrictions specified in the request.
   * </pre>
   *
   * <code>bool consistent = 1;</code>
   *
   * @return The consistent.
   */
  boolean getConsistent();
}
