// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/common.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public final class CommonProto extends com.google.protobuf.GeneratedFile {
  private CommonProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "CommonProto");
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_admin_v2_OperationProgress_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_bigtable_admin_v2_OperationProgress_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "%google/bigtable/admin/v2/common.proto\022"
          + "\030google.bigtable.admin.v2\032\037google/protobuf/timestamp.proto\"\213\001\n"
          + "\021OperationProgress\022\030\n"
          + "\020progress_percent\030\001 \001(\005\022.\n\n"
          + "start_time\030\002 \001(\0132\032.google.protobuf.Timestamp\022,\n"
          + "\010end_time\030\003 \001(\0132\032.google.protobuf.Timestamp*=\n"
          + "\013StorageType\022\034\n"
          + "\030STORAGE_TYPE_UNSPECIFIED\020\000\022\007\n"
          + "\003SSD\020\001\022\007\n"
          + "\003HDD\020\002B\316\001\n"
          + "\034com.google.bigtable.admin.v2B\013CommonProtoP\001Z8cloud.g"
          + "oogle.com/go/bigtable/admin/apiv2/adminp"
          + "b;adminpb\252\002\036Google.Cloud.Bigtable.Admin."
          + "V2\312\002\036Google\\Cloud\\Bigtable\\Admin\\V2\352\002\"Go"
          + "ogle::Cloud::Bigtable::Admin::V2b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_bigtable_admin_v2_OperationProgress_descriptor =
        getDescriptor().getMessageType(0);
    internal_static_google_bigtable_admin_v2_OperationProgress_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_google_bigtable_admin_v2_OperationProgress_descriptor,
            new java.lang.String[] {
              "ProgressPercent", "StartTime", "EndTime",
            });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
