// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_instance_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface CreateMaterializedViewMetadataOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.CreateMaterializedViewMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The request that prompted the initiation of this CreateMaterializedView
   * operation.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.CreateMaterializedViewRequest original_request = 1;</code>
   *
   * @return Whether the originalRequest field is set.
   */
  boolean hasOriginalRequest();

  /**
   *
   *
   * <pre>
   * The request that prompted the initiation of this CreateMaterializedView
   * operation.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.CreateMaterializedViewRequest original_request = 1;</code>
   *
   * @return The originalRequest.
   */
  com.google.bigtable.admin.v2.CreateMaterializedViewRequest getOriginalRequest();

  /**
   *
   *
   * <pre>
   * The request that prompted the initiation of this CreateMaterializedView
   * operation.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.CreateMaterializedViewRequest original_request = 1;</code>
   */
  com.google.bigtable.admin.v2.CreateMaterializedViewRequestOrBuilder getOriginalRequestOrBuilder();

  /**
   *
   *
   * <pre>
   * The time at which this operation started.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   *
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();

  /**
   *
   *
   * <pre>
   * The time at which this operation started.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   *
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();

  /**
   *
   *
   * <pre>
   * The time at which this operation started.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   *
   *
   * <pre>
   * If set, the time at which this operation finished or was canceled.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 3;</code>
   *
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();

  /**
   *
   *
   * <pre>
   * If set, the time at which this operation finished or was canceled.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 3;</code>
   *
   * @return The endTime.
   */
  com.google.protobuf.Timestamp getEndTime();

  /**
   *
   *
   * <pre>
   * If set, the time at which this operation finished or was canceled.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();
}
