// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_table_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface CreateSchemaBundleRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.CreateSchemaBundleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The parent resource where this schema bundle will be created.
   * Values are of the form
   * `projects/{project}/instances/{instance}/tables/{table}`.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The parent.
   */
  java.lang.String getParent();

  /**
   *
   *
   * <pre>
   * Required. The parent resource where this schema bundle will be created.
   * Values are of the form
   * `projects/{project}/instances/{instance}/tables/{table}`.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString getParentBytes();

  /**
   *
   *
   * <pre>
   * Required. The unique ID to use for the schema bundle, which will become the
   * final component of the schema bundle's resource name.
   * </pre>
   *
   * <code>string schema_bundle_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The schemaBundleId.
   */
  java.lang.String getSchemaBundleId();

  /**
   *
   *
   * <pre>
   * Required. The unique ID to use for the schema bundle, which will become the
   * final component of the schema bundle's resource name.
   * </pre>
   *
   * <code>string schema_bundle_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for schemaBundleId.
   */
  com.google.protobuf.ByteString getSchemaBundleIdBytes();

  /**
   *
   *
   * <pre>
   * Required. The schema bundle to create.
   * </pre>
   *
   * <code>
   * .google.bigtable.admin.v2.SchemaBundle schema_bundle = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the schemaBundle field is set.
   */
  boolean hasSchemaBundle();

  /**
   *
   *
   * <pre>
   * Required. The schema bundle to create.
   * </pre>
   *
   * <code>
   * .google.bigtable.admin.v2.SchemaBundle schema_bundle = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The schemaBundle.
   */
  com.google.bigtable.admin.v2.SchemaBundle getSchemaBundle();

  /**
   *
   *
   * <pre>
   * Required. The schema bundle to create.
   * </pre>
   *
   * <code>
   * .google.bigtable.admin.v2.SchemaBundle schema_bundle = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.bigtable.admin.v2.SchemaBundleOrBuilder getSchemaBundleOrBuilder();
}
