// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_table_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface DataBoostReadLocalWritesOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.DataBoostReadLocalWrites)
    com.google.protobuf.MessageOrBuilder {}
