// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_instance_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface DeleteLogicalViewRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.DeleteLogicalViewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The unique name of the logical view to be deleted.
   * Format:
   * `projects/{project}/instances/{instance}/logicalViews/{logical_view}`.
   * </pre>
   *
   * <code>
   * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   *
   *
   * <pre>
   * Required. The unique name of the logical view to be deleted.
   * Format:
   * `projects/{project}/instances/{instance}/logicalViews/{logical_view}`.
   * </pre>
   *
   * <code>
   * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   *
   *
   * <pre>
   * Optional. The current etag of the logical view.
   * If an etag is provided and does not match the current etag of the
   * logical view, deletion will be blocked and an ABORTED error will be
   * returned.
   * </pre>
   *
   * <code>string etag = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The etag.
   */
  java.lang.String getEtag();

  /**
   *
   *
   * <pre>
   * Optional. The current etag of the logical view.
   * If an etag is provided and does not match the current etag of the
   * logical view, deletion will be blocked and an ABORTED error will be
   * returned.
   * </pre>
   *
   * <code>string etag = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for etag.
   */
  com.google.protobuf.ByteString getEtagBytes();
}
