// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_table_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface GenerateConsistencyTokenResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.GenerateConsistencyTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The generated consistency token.
   * </pre>
   *
   * <code>string consistency_token = 1;</code>
   *
   * @return The consistencyToken.
   */
  java.lang.String getConsistencyToken();

  /**
   *
   *
   * <pre>
   * The generated consistency token.
   * </pre>
   *
   * <code>string consistency_token = 1;</code>
   *
   * @return The bytes for consistencyToken.
   */
  com.google.protobuf.ByteString getConsistencyTokenBytes();
}
