// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/bigtable_instance_admin.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface ListMaterializedViewsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.ListMaterializedViewsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The list of requested materialized views.
   * </pre>
   *
   * <code>repeated .google.bigtable.admin.v2.MaterializedView materialized_views = 1;</code>
   */
  java.util.List<com.google.bigtable.admin.v2.MaterializedView> getMaterializedViewsList();

  /**
   *
   *
   * <pre>
   * The list of requested materialized views.
   * </pre>
   *
   * <code>repeated .google.bigtable.admin.v2.MaterializedView materialized_views = 1;</code>
   */
  com.google.bigtable.admin.v2.MaterializedView getMaterializedViews(int index);

  /**
   *
   *
   * <pre>
   * The list of requested materialized views.
   * </pre>
   *
   * <code>repeated .google.bigtable.admin.v2.MaterializedView materialized_views = 1;</code>
   */
  int getMaterializedViewsCount();

  /**
   *
   *
   * <pre>
   * The list of requested materialized views.
   * </pre>
   *
   * <code>repeated .google.bigtable.admin.v2.MaterializedView materialized_views = 1;</code>
   */
  java.util.List<? extends com.google.bigtable.admin.v2.MaterializedViewOrBuilder>
      getMaterializedViewsOrBuilderList();

  /**
   *
   *
   * <pre>
   * The list of requested materialized views.
   * </pre>
   *
   * <code>repeated .google.bigtable.admin.v2.MaterializedView materialized_views = 1;</code>
   */
  com.google.bigtable.admin.v2.MaterializedViewOrBuilder getMaterializedViewsOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();

  /**
   *
   *
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString getNextPageTokenBytes();
}
