// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/instance.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface MaterializedViewOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.MaterializedView)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Identifier. The unique name of the materialized view.
   * Format:
   * `projects/{project}/instances/{instance}/materializedViews/{materialized_view}`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IDENTIFIER];</code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   *
   *
   * <pre>
   * Identifier. The unique name of the materialized view.
   * Format:
   * `projects/{project}/instances/{instance}/materializedViews/{materialized_view}`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IDENTIFIER];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   *
   *
   * <pre>
   * Required. Immutable. The materialized view's select query.
   * </pre>
   *
   * <code>
   * string query = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];
   * </code>
   *
   * @return The query.
   */
  java.lang.String getQuery();

  /**
   *
   *
   * <pre>
   * Required. Immutable. The materialized view's select query.
   * </pre>
   *
   * <code>
   * string query = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];
   * </code>
   *
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString getQueryBytes();

  /**
   *
   *
   * <pre>
   * Optional. The etag for this materialized view.
   * This may be sent on update requests to ensure that the client has an
   * up-to-date value before proceeding. The server returns an ABORTED error on
   * a mismatched etag.
   * </pre>
   *
   * <code>string etag = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The etag.
   */
  java.lang.String getEtag();

  /**
   *
   *
   * <pre>
   * Optional. The etag for this materialized view.
   * This may be sent on update requests to ensure that the client has an
   * up-to-date value before proceeding. The server returns an ABORTED error on
   * a mismatched etag.
   * </pre>
   *
   * <code>string etag = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for etag.
   */
  com.google.protobuf.ByteString getEtagBytes();

  /**
   *
   *
   * <pre>
   * Set to true to make the MaterializedView protected against deletion.
   * </pre>
   *
   * <code>bool deletion_protection = 6;</code>
   *
   * @return The deletionProtection.
   */
  boolean getDeletionProtection();
}
