// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/admin/v2/table.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.admin.v2;

@com.google.protobuf.Generated
public interface ProtoSchemaOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.ProtoSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. Contains a protobuf-serialized
   * [google.protobuf.FileDescriptorSet](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/descriptor.proto),
   * which could include multiple proto files.
   * To generate it, [install](https://grpc.io/docs/protoc-installation/) and
   * run `protoc` with
   * `--include_imports` and `--descriptor_set_out`. For example, to generate
   * for moon/shot/app.proto, run
   * ```
   * $protoc  --proto_path=/app_path --proto_path=/lib_path &#92;
   * --include_imports &#92;
   * --descriptor_set_out=descriptors.pb &#92;
   * moon/shot/app.proto
   * ```
   * For more details, see protobuffer [self
   * description](https://developers.google.com/protocol-buffers/docs/techniques#self-description).
   * </pre>
   *
   * <code>bytes proto_descriptors = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The protoDescriptors.
   */
  com.google.protobuf.ByteString getProtoDescriptors();
}
