// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/data.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface ProtoSchemaOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ProtoSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The columns in the result set.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ColumnMetadata columns = 1;</code>
   */
  java.util.List<com.google.bigtable.v2.ColumnMetadata> getColumnsList();

  /**
   *
   *
   * <pre>
   * The columns in the result set.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ColumnMetadata columns = 1;</code>
   */
  com.google.bigtable.v2.ColumnMetadata getColumns(int index);

  /**
   *
   *
   * <pre>
   * The columns in the result set.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ColumnMetadata columns = 1;</code>
   */
  int getColumnsCount();

  /**
   *
   *
   * <pre>
   * The columns in the result set.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ColumnMetadata columns = 1;</code>
   */
  java.util.List<? extends com.google.bigtable.v2.ColumnMetadataOrBuilder>
      getColumnsOrBuilderList();

  /**
   *
   *
   * <pre>
   * The columns in the result set.
   * </pre>
   *
   * <code>repeated .google.bigtable.v2.ColumnMetadata columns = 1;</code>
   */
  com.google.bigtable.v2.ColumnMetadataOrBuilder getColumnsOrBuilder(int index);
}
