// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/data.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface ProtoFormatOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ProtoFormat)
    com.google.protobuf.MessageOrBuilder {}
