// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/bigtable/v2/data.proto
// Protobuf Java Version: 4.33.0

package com.google.bigtable.v2;

@com.google.protobuf.Generated
public interface StreamPartitionOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.StreamPartition)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The row range covered by this partition and is specified by
   * [`start_key_closed`, `end_key_open`).
   * </pre>
   *
   * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
   *
   * @return Whether the rowRange field is set.
   */
  boolean hasRowRange();

  /**
   *
   *
   * <pre>
   * The row range covered by this partition and is specified by
   * [`start_key_closed`, `end_key_open`).
   * </pre>
   *
   * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
   *
   * @return The rowRange.
   */
  com.google.bigtable.v2.RowRange getRowRange();

  /**
   *
   *
   * <pre>
   * The row range covered by this partition and is specified by
   * [`start_key_closed`, `end_key_open`).
   * </pre>
   *
   * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
   */
  com.google.bigtable.v2.RowRangeOrBuilder getRowRangeOrBuilder();
}
