// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/admin/v2/instance.proto

package com.google.bigtable.admin.v2;

public interface AutoscalingTargetsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.AutoscalingTargets)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The cpu utilization that the Autoscaler should be trying to achieve.
   * This number is on a scale from 0 (no utilization) to
   * 100 (total utilization), and is limited between 10 and 80, otherwise it
   * will return INVALID_ARGUMENT error.
   * </pre>
   *
   * <code>int32 cpu_utilization_percent = 2;</code>
   * @return The cpuUtilizationPercent.
   */
  int getCpuUtilizationPercent();

  /**
   * <pre>
   * The storage utilization that the Autoscaler should be trying to achieve.
   * This number is limited between 2560 (2.5TiB) and 5120 (5TiB) for a SSD
   * cluster and between 8192 (8TiB) and 16384 (16TiB) for an HDD cluster;
   * otherwise it will return INVALID_ARGUMENT error. If this value is set to 0,
   * it will be treated as if it were set to the default value: 2560 for SSD,
   * 8192 for HDD.
   * </pre>
   *
   * <code>int32 storage_utilization_gib_per_node = 3;</code>
   * @return The storageUtilizationGibPerNode.
   */
  int getStorageUtilizationGibPerNode();
}
