// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/admin/v2/bigtable_table_admin.proto

// Protobuf Java Version: 3.25.3
package com.google.bigtable.admin.v2;

public interface CopyBackupMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.CopyBackupMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the backup being created through the copy operation.
   * Values are of the form
   * `projects/&lt;project&gt;/instances/&lt;instance&gt;/clusters/&lt;cluster&gt;/backups/&lt;backup&gt;`.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.resource_reference) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the backup being created through the copy operation.
   * Values are of the form
   * `projects/&lt;project&gt;/instances/&lt;instance&gt;/clusters/&lt;cluster&gt;/backups/&lt;backup&gt;`.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.resource_reference) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Information about the source backup that is being copied from.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.BackupInfo source_backup_info = 2;</code>
   * @return Whether the sourceBackupInfo field is set.
   */
  boolean hasSourceBackupInfo();
  /**
   * <pre>
   * Information about the source backup that is being copied from.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.BackupInfo source_backup_info = 2;</code>
   * @return The sourceBackupInfo.
   */
  com.google.bigtable.admin.v2.BackupInfo getSourceBackupInfo();
  /**
   * <pre>
   * Information about the source backup that is being copied from.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.BackupInfo source_backup_info = 2;</code>
   */
  com.google.bigtable.admin.v2.BackupInfoOrBuilder getSourceBackupInfoOrBuilder();

  /**
   * <pre>
   * The progress of the
   * [CopyBackup][google.bigtable.admin.v2.BigtableTableAdmin.CopyBackup]
   * operation.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.OperationProgress progress = 3;</code>
   * @return Whether the progress field is set.
   */
  boolean hasProgress();
  /**
   * <pre>
   * The progress of the
   * [CopyBackup][google.bigtable.admin.v2.BigtableTableAdmin.CopyBackup]
   * operation.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.OperationProgress progress = 3;</code>
   * @return The progress.
   */
  com.google.bigtable.admin.v2.OperationProgress getProgress();
  /**
   * <pre>
   * The progress of the
   * [CopyBackup][google.bigtable.admin.v2.BigtableTableAdmin.CopyBackup]
   * operation.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.OperationProgress progress = 3;</code>
   */
  com.google.bigtable.admin.v2.OperationProgressOrBuilder getProgressOrBuilder();
}
