// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/admin/v2/bigtable_table_admin.proto

package com.google.bigtable.admin.v2;

public interface DropRowRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.DropRowRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The unique name of the table on which to drop a range of rows.
   * Values are of the form
   * `projects/{project}/instances/{instance}/tables/{table}`.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. The unique name of the table on which to drop a range of rows.
   * Values are of the form
   * `projects/{project}/instances/{instance}/tables/{table}`.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Delete all rows that start with this row key prefix. Prefix cannot be
   * zero length.
   * </pre>
   *
   * <code>bytes row_key_prefix = 2;</code>
   * @return Whether the rowKeyPrefix field is set.
   */
  boolean hasRowKeyPrefix();
  /**
   * <pre>
   * Delete all rows that start with this row key prefix. Prefix cannot be
   * zero length.
   * </pre>
   *
   * <code>bytes row_key_prefix = 2;</code>
   * @return The rowKeyPrefix.
   */
  com.google.protobuf.ByteString getRowKeyPrefix();

  /**
   * <pre>
   * Delete all rows in the table. Setting this to false is a no-op.
   * </pre>
   *
   * <code>bool delete_all_data_from_table = 3;</code>
   * @return Whether the deleteAllDataFromTable field is set.
   */
  boolean hasDeleteAllDataFromTable();
  /**
   * <pre>
   * Delete all rows in the table. Setting this to false is a no-op.
   * </pre>
   *
   * <code>bool delete_all_data_from_table = 3;</code>
   * @return The deleteAllDataFromTable.
   */
  boolean getDeleteAllDataFromTable();

  public com.google.bigtable.admin.v2.DropRowRangeRequest.TargetCase getTargetCase();
}
