// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/admin/v2/bigtable_instance_admin.proto

package com.google.bigtable.admin.v2;

public interface UpdateAppProfileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.admin.v2.UpdateAppProfileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. The app profile which will (partially) replace the current value.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.AppProfile app_profile = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the appProfile field is set.
   */
  boolean hasAppProfile();
  /**
   * <pre>
   * Required. The app profile which will (partially) replace the current value.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.AppProfile app_profile = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The appProfile.
   */
  com.google.bigtable.admin.v2.AppProfile getAppProfile();
  /**
   * <pre>
   * Required. The app profile which will (partially) replace the current value.
   * </pre>
   *
   * <code>.google.bigtable.admin.v2.AppProfile app_profile = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.bigtable.admin.v2.AppProfileOrBuilder getAppProfileOrBuilder();

  /**
   * <pre>
   * Required. The subset of app profile fields which should be replaced.
   * If unset, all fields will be replaced.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * Required. The subset of app profile fields which should be replaced.
   * If unset, all fields will be replaced.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * Required. The subset of app profile fields which should be replaced.
   * If unset, all fields will be replaced.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();

  /**
   * <pre>
   * If true, ignore safety checks when updating the app profile.
   * </pre>
   *
   * <code>bool ignore_warnings = 3;</code>
   * @return The ignoreWarnings.
   */
  boolean getIgnoreWarnings();
}
