/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/bigtable.proto

// Protobuf Java Version: 3.25.5
package com.google.bigtable.v2;

public final class BigtableProto {
  private BigtableProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadRowsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadRowsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadRowsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadRowsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadRowsResponse_CellChunk_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadRowsResponse_CellChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_SampleRowKeysRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SampleRowKeysRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_SampleRowKeysResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_SampleRowKeysResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_MutateRowRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MutateRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_MutateRowResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MutateRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_MutateRowsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MutateRowsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_MutateRowsRequest_Entry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MutateRowsRequest_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_MutateRowsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MutateRowsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_MutateRowsResponse_Entry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_MutateRowsResponse_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_RateLimitInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_RateLimitInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_CheckAndMutateRowRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_CheckAndMutateRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_CheckAndMutateRowResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_CheckAndMutateRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_PingAndWarmRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PingAndWarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_PingAndWarmResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PingAndWarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadModifyWriteRowRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadModifyWriteRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadModifyWriteRowResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadModifyWriteRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_ChunkInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_ChunkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_DataChange_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_DataChange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_Heartbeat_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_CloseStream_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ReadChangeStreamResponse_CloseStream_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ExecuteQueryRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ExecuteQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ExecuteQueryRequest_ParamsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ExecuteQueryRequest_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_ExecuteQueryResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_ExecuteQueryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_PrepareQueryRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PrepareQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_PrepareQueryRequest_ParamTypesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PrepareQueryRequest_ParamTypesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_bigtable_v2_PrepareQueryResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_bigtable_v2_PrepareQueryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n!google/bigtable/v2/bigtable.proto\022\022goo"
          + "gle.bigtable.v2\032\034google/api/annotations."
          + "proto\032\027google/api/client.proto\032\037google/a"
          + "pi/field_behavior.proto\032\031google/api/reso"
          + "urce.proto\032\030google/api/routing.proto\032\035go"
          + "ogle/bigtable/v2/data.proto\032&google/bigt"
          + "able/v2/request_stats.proto\032\036google/bigt"
          + "able/v2/types.proto\032\036google/protobuf/dur"
          + "ation.proto\032\037google/protobuf/timestamp.p"
          + "roto\032\036google/protobuf/wrappers.proto\032\027go"
          + "ogle/rpc/status.proto\"\365\003\n\017ReadRowsReques"
          + "t\022>\n\ntable_name\030\001 \001(\tB*\340A\001\372A$\n\"bigtablea"
          + "dmin.googleapis.com/Table\022Q\n\024authorized_"
          + "view_name\030\t \001(\tB3\340A\001\372A-\n+bigtableadmin.g"
          + "oogleapis.com/AuthorizedView\022\026\n\016app_prof"
          + "ile_id\030\005 \001(\t\022(\n\004rows\030\002 \001(\0132\032.google.bigt"
          + "able.v2.RowSet\022-\n\006filter\030\003 \001(\0132\035.google."
          + "bigtable.v2.RowFilter\022\022\n\nrows_limit\030\004 \001("
          + "\003\022P\n\022request_stats_view\030\006 \001(\01624.google.b"
          + "igtable.v2.ReadRowsRequest.RequestStatsV"
          + "iew\022\020\n\010reversed\030\007 \001(\010\"f\n\020RequestStatsVie"
          + "w\022\"\n\036REQUEST_STATS_VIEW_UNSPECIFIED\020\000\022\026\n"
          + "\022REQUEST_STATS_NONE\020\001\022\026\n\022REQUEST_STATS_F"
          + "ULL\020\002\"\261\003\n\020ReadRowsResponse\022>\n\006chunks\030\001 \003"
          + "(\0132..google.bigtable.v2.ReadRowsResponse"
          + ".CellChunk\022\034\n\024last_scanned_row_key\030\002 \001(\014"
          + "\0227\n\rrequest_stats\030\003 \001(\0132 .google.bigtabl"
          + "e.v2.RequestStats\032\205\002\n\tCellChunk\022\017\n\007row_k"
          + "ey\030\001 \001(\014\0221\n\013family_name\030\002 \001(\0132\034.google.p"
          + "rotobuf.StringValue\022.\n\tqualifier\030\003 \001(\0132\033"
          + ".google.protobuf.BytesValue\022\030\n\020timestamp"
          + "_micros\030\004 \001(\003\022\016\n\006labels\030\005 \003(\t\022\r\n\005value\030\006"
          + " \001(\014\022\022\n\nvalue_size\030\007 \001(\005\022\023\n\treset_row\030\010 "
          + "\001(\010H\000\022\024\n\ncommit_row\030\t \001(\010H\000B\014\n\nrow_statu"
          + "s\"\301\001\n\024SampleRowKeysRequest\022>\n\ntable_name"
          + "\030\001 \001(\tB*\340A\001\372A$\n\"bigtableadmin.googleapis"
          + ".com/Table\022Q\n\024authorized_view_name\030\004 \001(\t"
          + "B3\340A\001\372A-\n+bigtableadmin.googleapis.com/A"
          + "uthorizedView\022\026\n\016app_profile_id\030\002 \001(\t\">\n"
          + "\025SampleRowKeysResponse\022\017\n\007row_key\030\001 \001(\014\022"
          + "\024\n\014offset_bytes\030\002 \001(\003\"\211\002\n\020MutateRowReque"
          + "st\022>\n\ntable_name\030\001 \001(\tB*\340A\001\372A$\n\"bigtable"
          + "admin.googleapis.com/Table\022Q\n\024authorized"
          + "_view_name\030\006 \001(\tB3\340A\001\372A-\n+bigtableadmin."
          + "googleapis.com/AuthorizedView\022\026\n\016app_pro"
          + "file_id\030\004 \001(\t\022\024\n\007row_key\030\002 \001(\014B\003\340A\002\0224\n\tm"
          + "utations\030\003 \003(\0132\034.google.bigtable.v2.Muta"
          + "tionB\003\340A\002\"\023\n\021MutateRowResponse\"\321\002\n\021Mutat"
          + "eRowsRequest\022>\n\ntable_name\030\001 \001(\tB*\340A\001\372A$"
          + "\n\"bigtableadmin.googleapis.com/Table\022Q\n\024"
          + "authorized_view_name\030\005 \001(\tB3\340A\001\372A-\n+bigt"
          + "ableadmin.googleapis.com/AuthorizedView\022"
          + "\026\n\016app_profile_id\030\003 \001(\t\022A\n\007entries\030\002 \003(\013"
          + "2+.google.bigtable.v2.MutateRowsRequest."
          + "EntryB\003\340A\002\032N\n\005Entry\022\017\n\007row_key\030\001 \001(\014\0224\n\t"
          + "mutations\030\002 \003(\0132\034.google.bigtable.v2.Mut"
          + "ationB\003\340A\002\"\344\001\n\022MutateRowsResponse\022=\n\007ent"
          + "ries\030\001 \003(\0132,.google.bigtable.v2.MutateRo"
          + "wsResponse.Entry\022?\n\017rate_limit_info\030\003 \001("
          + "\0132!.google.bigtable.v2.RateLimitInfoH\000\210\001"
          + "\001\032:\n\005Entry\022\r\n\005index\030\001 \001(\003\022\"\n\006status\030\002 \001("
          + "\0132\022.google.rpc.StatusB\022\n\020_rate_limit_inf"
          + "o\"J\n\rRateLimitInfo\022)\n\006period\030\001 \001(\0132\031.goo"
          + "gle.protobuf.Duration\022\016\n\006factor\030\002 \001(\001\"\201\003"
          + "\n\030CheckAndMutateRowRequest\022>\n\ntable_name"
          + "\030\001 \001(\tB*\340A\001\372A$\n\"bigtableadmin.googleapis"
          + ".com/Table\022Q\n\024authorized_view_name\030\t \001(\t"
          + "B3\340A\001\372A-\n+bigtableadmin.googleapis.com/A"
          + "uthorizedView\022\026\n\016app_profile_id\030\007 \001(\t\022\024\n"
          + "\007row_key\030\002 \001(\014B\003\340A\002\0227\n\020predicate_filter\030"
          + "\006 \001(\0132\035.google.bigtable.v2.RowFilter\0224\n\016"
          + "true_mutations\030\004 \003(\0132\034.google.bigtable.v"
          + "2.Mutation\0225\n\017false_mutations\030\005 \003(\0132\034.go"
          + "ogle.bigtable.v2.Mutation\"6\n\031CheckAndMut"
          + "ateRowResponse\022\031\n\021predicate_matched\030\001 \001("
          + "\010\"i\n\022PingAndWarmRequest\022;\n\004name\030\001 \001(\tB-\340"
          + "A\002\372A\'\n%bigtableadmin.googleapis.com/Inst"
          + "ance\022\026\n\016app_profile_id\030\002 \001(\t\"\025\n\023PingAndW"
          + "armResponse\"\231\002\n\031ReadModifyWriteRowReques"
          + "t\022>\n\ntable_name\030\001 \001(\tB*\340A\001\372A$\n\"bigtablea"
          + "dmin.googleapis.com/Table\022Q\n\024authorized_"
          + "view_name\030\006 \001(\tB3\340A\001\372A-\n+bigtableadmin.g"
          + "oogleapis.com/AuthorizedView\022\026\n\016app_prof"
          + "ile_id\030\004 \001(\t\022\024\n\007row_key\030\002 \001(\014B\003\340A\002\022;\n\005ru"
          + "les\030\003 \003(\0132\'.google.bigtable.v2.ReadModif"
          + "yWriteRuleB\003\340A\002\"B\n\032ReadModifyWriteRowRes"
          + "ponse\022$\n\003row\030\001 \001(\0132\027.google.bigtable.v2."
          + "Row\"\206\001\n,GenerateInitialChangeStreamParti"
          + "tionsRequest\022>\n\ntable_name\030\001 \001(\tB*\340A\002\372A$"
          + "\n\"bigtableadmin.googleapis.com/Table\022\026\n\016"
          + "app_profile_id\030\002 \001(\t\"g\n-GenerateInitialC"
          + "hangeStreamPartitionsResponse\0226\n\tpartiti"
          + "on\030\001 \001(\0132#.google.bigtable.v2.StreamPart"
          + "ition\"\233\003\n\027ReadChangeStreamRequest\022>\n\ntab"
          + "le_name\030\001 \001(\tB*\340A\002\372A$\n\"bigtableadmin.goo"
          + "gleapis.com/Table\022\026\n\016app_profile_id\030\002 \001("
          + "\t\0226\n\tpartition\030\003 \001(\0132#.google.bigtable.v"
          + "2.StreamPartition\0220\n\nstart_time\030\004 \001(\0132\032."
          + "google.protobuf.TimestampH\000\022K\n\023continuat"
          + "ion_tokens\030\006 \001(\0132,.google.bigtable.v2.St"
          + "reamContinuationTokensH\000\022,\n\010end_time\030\005 \001"
          + "(\0132\032.google.protobuf.Timestamp\0225\n\022heartb"
          + "eat_duration\030\007 \001(\0132\031.google.protobuf.Dur"
          + "ationB\014\n\nstart_from\"\251\n\n\030ReadChangeStream"
          + "Response\022N\n\013data_change\030\001 \001(\01327.google.b"
          + "igtable.v2.ReadChangeStreamResponse.Data"
          + "ChangeH\000\022K\n\theartbeat\030\002 \001(\01326.google.big"
          + "table.v2.ReadChangeStreamResponse.Heartb"
          + "eatH\000\022P\n\014close_stream\030\003 \001(\01328.google.big"
          + "table.v2.ReadChangeStreamResponse.CloseS"
          + "treamH\000\032\364\001\n\rMutationChunk\022X\n\nchunk_info\030"
          + "\001 \001(\0132D.google.bigtable.v2.ReadChangeStr"
          + "eamResponse.MutationChunk.ChunkInfo\022.\n\010m"
          + "utation\030\002 \001(\0132\034.google.bigtable.v2.Mutat"
          + "ion\032Y\n\tChunkInfo\022\032\n\022chunked_value_size\030\001"
          + " \001(\005\022\034\n\024chunked_value_offset\030\002 \001(\005\022\022\n\nla"
          + "st_chunk\030\003 \001(\010\032\306\003\n\nDataChange\022J\n\004type\030\001 "
          + "\001(\0162<.google.bigtable.v2.ReadChangeStrea"
          + "mResponse.DataChange.Type\022\031\n\021source_clus"
          + "ter_id\030\002 \001(\t\022\017\n\007row_key\030\003 \001(\014\0224\n\020commit_"
          + "timestamp\030\004 \001(\0132\032.google.protobuf.Timest"
          + "amp\022\022\n\ntiebreaker\030\005 \001(\005\022J\n\006chunks\030\006 \003(\0132"
          + ":.google.bigtable.v2.ReadChangeStreamRes"
          + "ponse.MutationChunk\022\014\n\004done\030\010 \001(\010\022\r\n\005tok"
          + "en\030\t \001(\t\022;\n\027estimated_low_watermark\030\n \001("
          + "\0132\032.google.protobuf.Timestamp\"P\n\004Type\022\024\n"
          + "\020TYPE_UNSPECIFIED\020\000\022\010\n\004USER\020\001\022\026\n\022GARBAGE"
          + "_COLLECTION\020\002\022\020\n\014CONTINUATION\020\003\032\221\001\n\tHear"
          + "tbeat\022G\n\022continuation_token\030\001 \001(\0132+.goog"
          + "le.bigtable.v2.StreamContinuationToken\022;"
          + "\n\027estimated_low_watermark\030\002 \001(\0132\032.google"
          + ".protobuf.Timestamp\032\270\001\n\013CloseStream\022\"\n\006s"
          + "tatus\030\001 \001(\0132\022.google.rpc.Status\022H\n\023conti"
          + "nuation_tokens\030\002 \003(\0132+.google.bigtable.v"
          + "2.StreamContinuationToken\022;\n\016new_partiti"
          + "ons\030\003 \003(\0132#.google.bigtable.v2.StreamPar"
          + "titionB\017\n\rstream_record\"\241\003\n\023ExecuteQuery"
          + "Request\022D\n\rinstance_name\030\001 \001(\tB-\340A\002\372A\'\n%"
          + "bigtableadmin.googleapis.com/Instance\022\033\n"
          + "\016app_profile_id\030\002 \001(\tB\003\340A\001\022\024\n\005query\030\003 \001("
          + "\tB\005\030\001\340A\002\022\026\n\016prepared_query\030\t \001(\014\022;\n\014prot"
          + "o_format\030\004 \001(\0132\037.google.bigtable.v2.Prot"
          + "oFormatB\002\030\001H\000\022\031\n\014resume_token\030\010 \001(\014B\003\340A\001"
          + "\022H\n\006params\030\007 \003(\01323.google.bigtable.v2.Ex"
          + "ecuteQueryRequest.ParamsEntryB\003\340A\002\032H\n\013Pa"
          + "ramsEntry\022\013\n\003key\030\001 \001(\t\022(\n\005value\030\002 \001(\0132\031."
          + "google.bigtable.v2.Value:\0028\001B\r\n\013data_for"
          + "mat\"\226\001\n\024ExecuteQueryResponse\0229\n\010metadata"
          + "\030\001 \001(\0132%.google.bigtable.v2.ResultSetMet"
          + "adataH\000\0227\n\007results\030\002 \001(\0132$.google.bigtab"
          + "le.v2.PartialResultSetH\000B\n\n\010response\"\364\002\n"
          + "\023PrepareQueryRequest\022D\n\rinstance_name\030\001 "
          + "\001(\tB-\340A\002\372A\'\n%bigtableadmin.googleapis.co"
          + "m/Instance\022\033\n\016app_profile_id\030\002 \001(\tB\003\340A\001\022"
          + "\022\n\005query\030\003 \001(\tB\003\340A\002\0227\n\014proto_format\030\004 \001("
          + "\0132\037.google.bigtable.v2.ProtoFormatH\000\022Q\n\013"
          + "param_types\030\006 \003(\01327.google.bigtable.v2.P"
          + "repareQueryRequest.ParamTypesEntryB\003\340A\002\032"
          + "K\n\017ParamTypesEntry\022\013\n\003key\030\001 \001(\t\022\'\n\005value"
          + "\030\002 \001(\0132\030.google.bigtable.v2.Type:\0028\001B\r\n\013"
          + "data_format\"\230\001\n\024PrepareQueryResponse\0227\n\010"
          + "metadata\030\001 \001(\0132%.google.bigtable.v2.Resu"
          + "ltSetMetadata\022\026\n\016prepared_query\030\002 \001(\014\022/\n"
          + "\013valid_until\030\003 \001(\0132\032.google.protobuf.Tim"
          + "estamp2\311&\n\010Bigtable\022\333\003\n\010ReadRows\022#.googl"
          + "e.bigtable.v2.ReadRowsRequest\032$.google.b"
          + "igtable.v2.ReadRowsResponse\"\201\003\332A\ntable_n"
          + "ame\332A\031table_name,app_profile_id\202\323\344\223\002\232\001\"9"
          + "/v2/{table_name=projects/*/instances/*/t"
          + "ables/*}:readRows:\001*ZZ\"U/v2/{authorized_"
          + "view_name=projects/*/instances/*/tables/"
          + "*/authorizedViews/*}:readRows:\001*\212\323\344\223\002\260\001\022"
          + ":\n\ntable_name\022,{table_name=projects/*/in"
          + "stances/*/tables/*}\022\020\n\016app_profile_id\022`\n"
          + "\024authorized_view_name\022H{authorized_view_"
          + "name=projects/*/instances/*/tables/*/aut"
          + "horizedViews/*}0\001\022\356\003\n\rSampleRowKeys\022(.go"
          + "ogle.bigtable.v2.SampleRowKeysRequest\032)."
          + "google.bigtable.v2.SampleRowKeysResponse"
          + "\"\205\003\332A\ntable_name\332A\031table_name,app_profil"
          + "e_id\202\323\344\223\002\236\001\022>/v2/{table_name=projects/*/"
          + "instances/*/tables/*}:sampleRowKeysZ\\\022Z/"
          + "v2/{authorized_view_name=projects/*/inst"
          + "ances/*/tables/*/authorizedViews/*}:samp"
          + "leRowKeys\212\323\344\223\002\260\001\022:\n\ntable_name\022,{table_n"
          + "ame=projects/*/instances/*/tables/*}\022\020\n\016"
          + "app_profile_id\022`\n\024authorized_view_name\022H"
          + "{authorized_view_name=projects/*/instanc"
          + "es/*/tables/*/authorizedViews/*}0\001\022\202\004\n\tM"
          + "utateRow\022$.google.bigtable.v2.MutateRowR"
          + "equest\032%.google.bigtable.v2.MutateRowRes"
          + "ponse\"\247\003\332A\034table_name,row_key,mutations\332"
          + "A+table_name,row_key,mutations,app_profi"
          + "le_id\202\323\344\223\002\234\001\":/v2/{table_name=projects/*"
          + "/instances/*/tables/*}:mutateRow:\001*Z[\"V/"
          + "v2/{authorized_view_name=projects/*/inst"
          + "ances/*/tables/*/authorizedViews/*}:muta"
          + "teRow:\001*\212\323\344\223\002\260\001\022:\n\ntable_name\022,{table_na"
          + "me=projects/*/instances/*/tables/*}\022\020\n\016a"
          + "pp_profile_id\022`\n\024authorized_view_name\022H{"
          + "authorized_view_name=projects/*/instance"
          + "s/*/tables/*/authorizedViews/*}\022\365\003\n\nMuta"
          + "teRows\022%.google.bigtable.v2.MutateRowsRe"
          + "quest\032&.google.bigtable.v2.MutateRowsRes"
          + "ponse\"\225\003\332A\022table_name,entries\332A!table_na"
          + "me,entries,app_profile_id\202\323\344\223\002\236\001\";/v2/{t"
          + "able_name=projects/*/instances/*/tables/"
          + "*}:mutateRows:\001*Z\\\"W/v2/{authorized_view"
          + "_name=projects/*/instances/*/tables/*/au"
          + "thorizedViews/*}:mutateRows:\001*\212\323\344\223\002\260\001\022:\n"
          + "\ntable_name\022,{table_name=projects/*/inst"
          + "ances/*/tables/*}\022\020\n\016app_profile_id\022`\n\024a"
          + "uthorized_view_name\022H{authorized_view_na"
          + "me=projects/*/instances/*/tables/*/autho"
          + "rizedViews/*}0\001\022\366\004\n\021CheckAndMutateRow\022,."
          + "google.bigtable.v2.CheckAndMutateRowRequ"
          + "est\032-.google.bigtable.v2.CheckAndMutateR"
          + "owResponse\"\203\004\332ABtable_name,row_key,predi"
          + "cate_filter,true_mutations,false_mutatio"
          + "ns\332AQtable_name,row_key,predicate_filter"
          + ",true_mutations,false_mutations,app_prof"
          + "ile_id\202\323\344\223\002\254\001\"B/v2/{table_name=projects/"
          + "*/instances/*/tables/*}:checkAndMutateRo"
          + "w:\001*Zc\"^/v2/{authorized_view_name=projec"
          + "ts/*/instances/*/tables/*/authorizedView"
          + "s/*}:checkAndMutateRow:\001*\212\323\344\223\002\260\001\022:\n\ntabl"
          + "e_name\022,{table_name=projects/*/instances"
          + "/*/tables/*}\022\020\n\016app_profile_id\022`\n\024author"
          + "ized_view_name\022H{authorized_view_name=pr"
          + "ojects/*/instances/*/tables/*/authorized"
          + "Views/*}\022\356\001\n\013PingAndWarm\022&.google.bigtab"
          + "le.v2.PingAndWarmRequest\032\'.google.bigtab"
          + "le.v2.PingAndWarmResponse\"\215\001\332A\004name\332A\023na"
          + "me,app_profile_id\202\323\344\223\002+\"&/v2/{name=proje"
          + "cts/*/instances/*}:ping:\001*\212\323\344\223\0029\022%\n\004name"
          + "\022\035{name=projects/*/instances/*}\022\020\n\016app_p"
          + "rofile_id\022\247\004\n\022ReadModifyWriteRow\022-.googl"
          + "e.bigtable.v2.ReadModifyWriteRowRequest\032"
          + "..google.bigtable.v2.ReadModifyWriteRowR"
          + "esponse\"\261\003\332A\030table_name,row_key,rules\332A\'"
          + "table_name,row_key,rules,app_profile_id\202"
          + "\323\344\223\002\256\001\"C/v2/{table_name=projects/*/insta"
          + "nces/*/tables/*}:readModifyWriteRow:\001*Zd"
          + "\"_/v2/{authorized_view_name=projects/*/i"
          + "nstances/*/tables/*/authorizedViews/*}:r"
          + "eadModifyWriteRow:\001*\212\323\344\223\002\260\001\022:\n\ntable_nam"
          + "e\022,{table_name=projects/*/instances/*/ta"
          + "bles/*}\022\020\n\016app_profile_id\022`\n\024authorized_"
          + "view_name\022H{authorized_view_name=project"
          + "s/*/instances/*/tables/*/authorizedViews"
          + "/*}\022\273\002\n%GenerateInitialChangeStreamParti"
          + "tions\022@.google.bigtable.v2.GenerateIniti"
          + "alChangeStreamPartitionsRequest\032A.google"
          + ".bigtable.v2.GenerateInitialChangeStream"
          + "PartitionsResponse\"\212\001\332A\ntable_name\332A\031tab"
          + "le_name,app_profile_id\202\323\344\223\002[\"V/v2/{table"
          + "_name=projects/*/instances/*/tables/*}:g"
          + "enerateInitialChangeStreamPartitions:\001*0"
          + "\001\022\346\001\n\020ReadChangeStream\022+.google.bigtable"
          + ".v2.ReadChangeStreamRequest\032,.google.big"
          + "table.v2.ReadChangeStreamResponse\"u\332A\nta"
          + "ble_name\332A\031table_name,app_profile_id\202\323\344\223"
          + "\002F\"A/v2/{table_name=projects/*/instances"
          + "/*/tables/*}:readChangeStream:\001*0\001\022\251\002\n\014P"
          + "repareQuery\022\'.google.bigtable.v2.Prepare"
          + "QueryRequest\032(.google.bigtable.v2.Prepar"
          + "eQueryResponse\"\305\001\332A\023instance_name,query\332"
          + "A\"instance_name,query,app_profile_id\202\323\344\223"
          + "\002<\"7/v2/{instance_name=projects/*/instan"
          + "ces/*}:prepareQuery:\001*\212\323\344\223\002B\022.\n\rinstance"
          + "_name\022\035{name=projects/*/instances/*}\022\020\n\016"
          + "app_profile_id\022\253\002\n\014ExecuteQuery\022\'.google"
          + ".bigtable.v2.ExecuteQueryRequest\032(.googl"
          + "e.bigtable.v2.ExecuteQueryResponse\"\305\001\332A\023"
          + "instance_name,query\332A\"instance_name,quer"
          + "y,app_profile_id\202\323\344\223\002<\"7/v2/{instance_na"
          + "me=projects/*/instances/*}:executeQuery:"
          + "\001*\212\323\344\223\002B\022.\n\rinstance_name\022\035{name=project"
          + "s/*/instances/*}\022\020\n\016app_profile_id0\001\032\333\002\312"
          + "A\027bigtable.googleapis.com\322A\275\002https://www"
          + ".googleapis.com/auth/bigtable.data,https"
          + "://www.googleapis.com/auth/bigtable.data"
          + ".readonly,https://www.googleapis.com/aut"
          + "h/cloud-bigtable.data,https://www.google"
          + "apis.com/auth/cloud-bigtable.data.readon"
          + "ly,https://www.googleapis.com/auth/cloud"
          + "-platform,https://www.googleapis.com/aut"
          + "h/cloud-platform.read-onlyB\364\003\n\026com.googl"
          + "e.bigtable.v2B\rBigtableProtoP\001Z8cloud.go"
          + "ogle.com/go/bigtable/apiv2/bigtablepb;bi"
          + "gtablepb\252\002\030Google.Cloud.Bigtable.V2\312\002\030Go"
          + "ogle\\Cloud\\Bigtable\\V2\352\002\033Google::Cloud::"
          + "Bigtable::V2\352AP\n%bigtableadmin.googleapi"
          + "s.com/Instance\022\'projects/{project}/insta"
          + "nces/{instance}\352A\\\n\"bigtableadmin.google"
          + "apis.com/Table\0226projects/{project}/insta"
          + "nces/{instance}/tables/{table}\352A\207\001\n+bigt"
          + "ableadmin.googleapis.com/AuthorizedView\022"
          + "Xprojects/{project}/instances/{instance}"
          + "/tables/{table}/authorizedViews/{authori"
          + "zed_view}b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.api.RoutingProto.getDescriptor(),
              com.google.bigtable.v2.DataProto.getDescriptor(),
              com.google.bigtable.v2.RequestStatsProto.getDescriptor(),
              com.google.bigtable.v2.TypesProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.protobuf.WrappersProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
            });
    internal_static_google_bigtable_v2_ReadRowsRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_bigtable_v2_ReadRowsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadRowsRequest_descriptor,
            new java.lang.String[] {
              "TableName",
              "AuthorizedViewName",
              "AppProfileId",
              "Rows",
              "Filter",
              "RowsLimit",
              "RequestStatsView",
              "Reversed",
            });
    internal_static_google_bigtable_v2_ReadRowsResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_bigtable_v2_ReadRowsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadRowsResponse_descriptor,
            new java.lang.String[] {
              "Chunks", "LastScannedRowKey", "RequestStats",
            });
    internal_static_google_bigtable_v2_ReadRowsResponse_CellChunk_descriptor =
        internal_static_google_bigtable_v2_ReadRowsResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_ReadRowsResponse_CellChunk_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadRowsResponse_CellChunk_descriptor,
            new java.lang.String[] {
              "RowKey",
              "FamilyName",
              "Qualifier",
              "TimestampMicros",
              "Labels",
              "Value",
              "ValueSize",
              "ResetRow",
              "CommitRow",
              "RowStatus",
            });
    internal_static_google_bigtable_v2_SampleRowKeysRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_bigtable_v2_SampleRowKeysRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_SampleRowKeysRequest_descriptor,
            new java.lang.String[] {
              "TableName", "AuthorizedViewName", "AppProfileId",
            });
    internal_static_google_bigtable_v2_SampleRowKeysResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_bigtable_v2_SampleRowKeysResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_SampleRowKeysResponse_descriptor,
            new java.lang.String[] {
              "RowKey", "OffsetBytes",
            });
    internal_static_google_bigtable_v2_MutateRowRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_bigtable_v2_MutateRowRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_MutateRowRequest_descriptor,
            new java.lang.String[] {
              "TableName", "AuthorizedViewName", "AppProfileId", "RowKey", "Mutations",
            });
    internal_static_google_bigtable_v2_MutateRowResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_bigtable_v2_MutateRowResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_MutateRowResponse_descriptor,
            new java.lang.String[] {});
    internal_static_google_bigtable_v2_MutateRowsRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_bigtable_v2_MutateRowsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_MutateRowsRequest_descriptor,
            new java.lang.String[] {
              "TableName", "AuthorizedViewName", "AppProfileId", "Entries",
            });
    internal_static_google_bigtable_v2_MutateRowsRequest_Entry_descriptor =
        internal_static_google_bigtable_v2_MutateRowsRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_MutateRowsRequest_Entry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_MutateRowsRequest_Entry_descriptor,
            new java.lang.String[] {
              "RowKey", "Mutations",
            });
    internal_static_google_bigtable_v2_MutateRowsResponse_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_bigtable_v2_MutateRowsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_MutateRowsResponse_descriptor,
            new java.lang.String[] {
              "Entries", "RateLimitInfo",
            });
    internal_static_google_bigtable_v2_MutateRowsResponse_Entry_descriptor =
        internal_static_google_bigtable_v2_MutateRowsResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_MutateRowsResponse_Entry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_MutateRowsResponse_Entry_descriptor,
            new java.lang.String[] {
              "Index", "Status",
            });
    internal_static_google_bigtable_v2_RateLimitInfo_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_bigtable_v2_RateLimitInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_RateLimitInfo_descriptor,
            new java.lang.String[] {
              "Period", "Factor",
            });
    internal_static_google_bigtable_v2_CheckAndMutateRowRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_bigtable_v2_CheckAndMutateRowRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_CheckAndMutateRowRequest_descriptor,
            new java.lang.String[] {
              "TableName",
              "AuthorizedViewName",
              "AppProfileId",
              "RowKey",
              "PredicateFilter",
              "TrueMutations",
              "FalseMutations",
            });
    internal_static_google_bigtable_v2_CheckAndMutateRowResponse_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_bigtable_v2_CheckAndMutateRowResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_CheckAndMutateRowResponse_descriptor,
            new java.lang.String[] {
              "PredicateMatched",
            });
    internal_static_google_bigtable_v2_PingAndWarmRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_bigtable_v2_PingAndWarmRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_PingAndWarmRequest_descriptor,
            new java.lang.String[] {
              "Name", "AppProfileId",
            });
    internal_static_google_bigtable_v2_PingAndWarmResponse_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_bigtable_v2_PingAndWarmResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_PingAndWarmResponse_descriptor,
            new java.lang.String[] {});
    internal_static_google_bigtable_v2_ReadModifyWriteRowRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_bigtable_v2_ReadModifyWriteRowRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadModifyWriteRowRequest_descriptor,
            new java.lang.String[] {
              "TableName", "AuthorizedViewName", "AppProfileId", "RowKey", "Rules",
            });
    internal_static_google_bigtable_v2_ReadModifyWriteRowResponse_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_bigtable_v2_ReadModifyWriteRowResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadModifyWriteRowResponse_descriptor,
            new java.lang.String[] {
              "Row",
            });
    internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsRequest_descriptor,
            new java.lang.String[] {
              "TableName", "AppProfileId",
            });
    internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_GenerateInitialChangeStreamPartitionsResponse_descriptor,
            new java.lang.String[] {
              "Partition",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamRequest_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_bigtable_v2_ReadChangeStreamRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamRequest_descriptor,
            new java.lang.String[] {
              "TableName",
              "AppProfileId",
              "Partition",
              "StartTime",
              "ContinuationTokens",
              "EndTime",
              "HeartbeatDuration",
              "StartFrom",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor,
            new java.lang.String[] {
              "DataChange", "Heartbeat", "CloseStream", "StreamRecord",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_descriptor =
        internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_descriptor,
            new java.lang.String[] {
              "ChunkInfo", "Mutation",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_ChunkInfo_descriptor =
        internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_ChunkInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamResponse_MutationChunk_ChunkInfo_descriptor,
            new java.lang.String[] {
              "ChunkedValueSize", "ChunkedValueOffset", "LastChunk",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_DataChange_descriptor =
        internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_DataChange_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamResponse_DataChange_descriptor,
            new java.lang.String[] {
              "Type",
              "SourceClusterId",
              "RowKey",
              "CommitTimestamp",
              "Tiebreaker",
              "Chunks",
              "Done",
              "Token",
              "EstimatedLowWatermark",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_Heartbeat_descriptor =
        internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_Heartbeat_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamResponse_Heartbeat_descriptor,
            new java.lang.String[] {
              "ContinuationToken", "EstimatedLowWatermark",
            });
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_CloseStream_descriptor =
        internal_static_google_bigtable_v2_ReadChangeStreamResponse_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_bigtable_v2_ReadChangeStreamResponse_CloseStream_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ReadChangeStreamResponse_CloseStream_descriptor,
            new java.lang.String[] {
              "Status", "ContinuationTokens", "NewPartitions",
            });
    internal_static_google_bigtable_v2_ExecuteQueryRequest_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_bigtable_v2_ExecuteQueryRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ExecuteQueryRequest_descriptor,
            new java.lang.String[] {
              "InstanceName",
              "AppProfileId",
              "Query",
              "PreparedQuery",
              "ProtoFormat",
              "ResumeToken",
              "Params",
              "DataFormat",
            });
    internal_static_google_bigtable_v2_ExecuteQueryRequest_ParamsEntry_descriptor =
        internal_static_google_bigtable_v2_ExecuteQueryRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_ExecuteQueryRequest_ParamsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ExecuteQueryRequest_ParamsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_bigtable_v2_ExecuteQueryResponse_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_bigtable_v2_ExecuteQueryResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_ExecuteQueryResponse_descriptor,
            new java.lang.String[] {
              "Metadata", "Results", "Response",
            });
    internal_static_google_bigtable_v2_PrepareQueryRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_bigtable_v2_PrepareQueryRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_PrepareQueryRequest_descriptor,
            new java.lang.String[] {
              "InstanceName", "AppProfileId", "Query", "ProtoFormat", "ParamTypes", "DataFormat",
            });
    internal_static_google_bigtable_v2_PrepareQueryRequest_ParamTypesEntry_descriptor =
        internal_static_google_bigtable_v2_PrepareQueryRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_bigtable_v2_PrepareQueryRequest_ParamTypesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_PrepareQueryRequest_ParamTypesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_bigtable_v2_PrepareQueryResponse_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_bigtable_v2_PrepareQueryResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_bigtable_v2_PrepareQueryResponse_descriptor,
            new java.lang.String[] {
              "Metadata", "PreparedQuery", "ValidUntil",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.api.RoutingProto.routing);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.api.RoutingProto.getDescriptor();
    com.google.bigtable.v2.DataProto.getDescriptor();
    com.google.bigtable.v2.RequestStatsProto.getDescriptor();
    com.google.bigtable.v2.TypesProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
