// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/request_stats.proto

package com.google.bigtable.v2;

public interface FullReadStatsViewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.FullReadStatsView)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Iteration stats describe how efficient the read is, e.g. comparing
   * rows seen vs. rows returned or cells seen vs cells returned can provide an
   * indication of read efficiency (the higher the ratio of seen to retuned the
   * better).
   * </pre>
   *
   * <code>.google.bigtable.v2.ReadIterationStats read_iteration_stats = 1;</code>
   * @return Whether the readIterationStats field is set.
   */
  boolean hasReadIterationStats();
  /**
   * <pre>
   * Iteration stats describe how efficient the read is, e.g. comparing
   * rows seen vs. rows returned or cells seen vs cells returned can provide an
   * indication of read efficiency (the higher the ratio of seen to retuned the
   * better).
   * </pre>
   *
   * <code>.google.bigtable.v2.ReadIterationStats read_iteration_stats = 1;</code>
   * @return The readIterationStats.
   */
  com.google.bigtable.v2.ReadIterationStats getReadIterationStats();
  /**
   * <pre>
   * Iteration stats describe how efficient the read is, e.g. comparing
   * rows seen vs. rows returned or cells seen vs cells returned can provide an
   * indication of read efficiency (the higher the ratio of seen to retuned the
   * better).
   * </pre>
   *
   * <code>.google.bigtable.v2.ReadIterationStats read_iteration_stats = 1;</code>
   */
  com.google.bigtable.v2.ReadIterationStatsOrBuilder getReadIterationStatsOrBuilder();

  /**
   * <pre>
   * Request latency stats describe the time taken to complete a request, from
   * the server side.
   * </pre>
   *
   * <code>.google.bigtable.v2.RequestLatencyStats request_latency_stats = 2;</code>
   * @return Whether the requestLatencyStats field is set.
   */
  boolean hasRequestLatencyStats();
  /**
   * <pre>
   * Request latency stats describe the time taken to complete a request, from
   * the server side.
   * </pre>
   *
   * <code>.google.bigtable.v2.RequestLatencyStats request_latency_stats = 2;</code>
   * @return The requestLatencyStats.
   */
  com.google.bigtable.v2.RequestLatencyStats getRequestLatencyStats();
  /**
   * <pre>
   * Request latency stats describe the time taken to complete a request, from
   * the server side.
   * </pre>
   *
   * <code>.google.bigtable.v2.RequestLatencyStats request_latency_stats = 2;</code>
   */
  com.google.bigtable.v2.RequestLatencyStatsOrBuilder getRequestLatencyStatsOrBuilder();
}
