// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/bigtable.proto

package com.google.bigtable.v2;

public interface PingAndWarmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.PingAndWarmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Data received from the server.
   * </pre>
   *
   * <code>bytes ping_data = 1;</code>
   * @return The pingData.
   */
  com.google.protobuf.ByteString getPingData();
}
