/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/data.proto

package com.google.bigtable.v2;

/**
 *
 *
 * <pre>
 * NOTE: This API is not generally available. Users must be allowlisted.
 * A partition of a change stream.
 * </pre>
 *
 * Protobuf type {@code google.bigtable.v2.StreamPartition}
 */
public final class StreamPartition extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.bigtable.v2.StreamPartition)
    StreamPartitionOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use StreamPartition.newBuilder() to construct.
  private StreamPartition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private StreamPartition() {}

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new StreamPartition();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private StreamPartition(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              RowRange.Builder subBuilder = null;
              if (rowRange_ != null) {
                subBuilder = rowRange_.toBuilder();
              }
              rowRange_ = input.readMessage(RowRange.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(rowRange_);
                rowRange_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return DataProto.internal_static_google_bigtable_v2_StreamPartition_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return DataProto.internal_static_google_bigtable_v2_StreamPartition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(StreamPartition.class, Builder.class);
  }

  public static final int ROW_RANGE_FIELD_NUMBER = 1;
  private RowRange rowRange_;
  /**
   *
   *
   * <pre>
   * The row range covered by this partition and is specified by
   * [`start_key_closed`, `end_key_open`).
   * </pre>
   *
   * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
   *
   * @return Whether the rowRange field is set.
   */
  @Override
  public boolean hasRowRange() {
    return rowRange_ != null;
  }
  /**
   *
   *
   * <pre>
   * The row range covered by this partition and is specified by
   * [`start_key_closed`, `end_key_open`).
   * </pre>
   *
   * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
   *
   * @return The rowRange.
   */
  @Override
  public RowRange getRowRange() {
    return rowRange_ == null ? RowRange.getDefaultInstance() : rowRange_;
  }
  /**
   *
   *
   * <pre>
   * The row range covered by this partition and is specified by
   * [`start_key_closed`, `end_key_open`).
   * </pre>
   *
   * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
   */
  @Override
  public RowRangeOrBuilder getRowRangeOrBuilder() {
    return getRowRange();
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (rowRange_ != null) {
      output.writeMessage(1, getRowRange());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rowRange_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getRowRange());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof StreamPartition)) {
      return super.equals(obj);
    }
    StreamPartition other = (StreamPartition) obj;

    if (hasRowRange() != other.hasRowRange()) return false;
    if (hasRowRange()) {
      if (!getRowRange().equals(other.getRowRange())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRowRange()) {
      hash = (37 * hash) + ROW_RANGE_FIELD_NUMBER;
      hash = (53 * hash) + getRowRange().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static StreamPartition parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static StreamPartition parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static StreamPartition parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static StreamPartition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static StreamPartition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static StreamPartition parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static StreamPartition parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static StreamPartition parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static StreamPartition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static StreamPartition parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static StreamPartition parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static StreamPartition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(StreamPartition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * NOTE: This API is not generally available. Users must be allowlisted.
   * A partition of a change stream.
   * </pre>
   *
   * Protobuf type {@code google.bigtable.v2.StreamPartition}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.bigtable.v2.StreamPartition)
      StreamPartitionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return DataProto.internal_static_google_bigtable_v2_StreamPartition_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return DataProto.internal_static_google_bigtable_v2_StreamPartition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(StreamPartition.class, Builder.class);
    }

    // Construct using com.google.bigtable.v2.StreamPartition.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      if (rowRangeBuilder_ == null) {
        rowRange_ = null;
      } else {
        rowRange_ = null;
        rowRangeBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return DataProto.internal_static_google_bigtable_v2_StreamPartition_descriptor;
    }

    @Override
    public StreamPartition getDefaultInstanceForType() {
      return StreamPartition.getDefaultInstance();
    }

    @Override
    public StreamPartition build() {
      StreamPartition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public StreamPartition buildPartial() {
      StreamPartition result = new StreamPartition(this);
      if (rowRangeBuilder_ == null) {
        result.rowRange_ = rowRange_;
      } else {
        result.rowRange_ = rowRangeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof StreamPartition) {
        return mergeFrom((StreamPartition) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(StreamPartition other) {
      if (other == StreamPartition.getDefaultInstance()) return this;
      if (other.hasRowRange()) {
        mergeRowRange(other.getRowRange());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      StreamPartition parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (StreamPartition) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private RowRange rowRange_;
    private com.google.protobuf.SingleFieldBuilderV3<RowRange, RowRange.Builder, RowRangeOrBuilder>
        rowRangeBuilder_;
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     *
     * @return Whether the rowRange field is set.
     */
    public boolean hasRowRange() {
      return rowRangeBuilder_ != null || rowRange_ != null;
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     *
     * @return The rowRange.
     */
    public RowRange getRowRange() {
      if (rowRangeBuilder_ == null) {
        return rowRange_ == null ? RowRange.getDefaultInstance() : rowRange_;
      } else {
        return rowRangeBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    public Builder setRowRange(RowRange value) {
      if (rowRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rowRange_ = value;
        onChanged();
      } else {
        rowRangeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    public Builder setRowRange(RowRange.Builder builderForValue) {
      if (rowRangeBuilder_ == null) {
        rowRange_ = builderForValue.build();
        onChanged();
      } else {
        rowRangeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    public Builder mergeRowRange(RowRange value) {
      if (rowRangeBuilder_ == null) {
        if (rowRange_ != null) {
          rowRange_ = RowRange.newBuilder(rowRange_).mergeFrom(value).buildPartial();
        } else {
          rowRange_ = value;
        }
        onChanged();
      } else {
        rowRangeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    public Builder clearRowRange() {
      if (rowRangeBuilder_ == null) {
        rowRange_ = null;
        onChanged();
      } else {
        rowRange_ = null;
        rowRangeBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    public RowRange.Builder getRowRangeBuilder() {

      onChanged();
      return getRowRangeFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    public RowRangeOrBuilder getRowRangeOrBuilder() {
      if (rowRangeBuilder_ != null) {
        return rowRangeBuilder_.getMessageOrBuilder();
      } else {
        return rowRange_ == null ? RowRange.getDefaultInstance() : rowRange_;
      }
    }
    /**
     *
     *
     * <pre>
     * The row range covered by this partition and is specified by
     * [`start_key_closed`, `end_key_open`).
     * </pre>
     *
     * <code>.google.bigtable.v2.RowRange row_range = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<RowRange, RowRange.Builder, RowRangeOrBuilder>
        getRowRangeFieldBuilder() {
      if (rowRangeBuilder_ == null) {
        rowRangeBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                RowRange, RowRange.Builder, RowRangeOrBuilder>(
                getRowRange(), getParentForChildren(), isClean());
        rowRange_ = null;
      }
      return rowRangeBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.bigtable.v2.StreamPartition)
  }

  // @@protoc_insertion_point(class_scope:google.bigtable.v2.StreamPartition)
  private static final StreamPartition DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new StreamPartition();
  }

  public static StreamPartition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamPartition> PARSER =
      new com.google.protobuf.AbstractParser<StreamPartition>() {
        @Override
        public StreamPartition parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new StreamPartition(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<StreamPartition> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<StreamPartition> getParserForType() {
    return PARSER;
  }

  @Override
  public StreamPartition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
