// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/feature_flags.proto

package com.google.bigtable.v2;

public interface FeatureFlagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.FeatureFlags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Notify the server that the client supports reverse scans. The server will
   * reject ReadRowsRequests with the reverse bit set when this is absent.
   * </pre>
   *
   * <code>bool reverse_scans = 1;</code>
   * @return The reverseScans.
   */
  boolean getReverseScans();

  /**
   * <pre>
   * Notify the server that the client enables batch write flow control by
   * requesting RateLimitInfo from MutateRowsResponse.
   * </pre>
   *
   * <code>bool mutate_rows_rate_limit = 3;</code>
   * @return The mutateRowsRateLimit.
   */
  boolean getMutateRowsRateLimit();
}
