// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/data.proto

// Protobuf Java Version: 3.25.3
package com.google.bigtable.v2;

public interface ProtoRowsBatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ProtoRowsBatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Merge partial results by concatenating these bytes, then parsing the
   * overall value as a `ProtoRows` message.
   * </pre>
   *
   * <code>bytes batch_data = 1;</code>
   * @return The batchData.
   */
  com.google.protobuf.ByteString getBatchData();
}
