// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/data.proto

// Protobuf Java Version: 3.25.3
package com.google.bigtable.v2;

public interface ProtoFormatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ProtoFormat)
    com.google.protobuf.MessageOrBuilder {
}
