// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/bigtable/v2/data.proto

// Protobuf Java Version: 3.25.3
package com.google.bigtable.v2;

public interface ResultSetMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.ResultSetMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Schema in proto format
   * </pre>
   *
   * <code>.google.bigtable.v2.ProtoSchema proto_schema = 1;</code>
   * @return Whether the protoSchema field is set.
   */
  boolean hasProtoSchema();
  /**
   * <pre>
   * Schema in proto format
   * </pre>
   *
   * <code>.google.bigtable.v2.ProtoSchema proto_schema = 1;</code>
   * @return The protoSchema.
   */
  com.google.bigtable.v2.ProtoSchema getProtoSchema();
  /**
   * <pre>
   * Schema in proto format
   * </pre>
   *
   * <code>.google.bigtable.v2.ProtoSchema proto_schema = 1;</code>
   */
  com.google.bigtable.v2.ProtoSchemaOrBuilder getProtoSchemaOrBuilder();

  com.google.bigtable.v2.ResultSetMetadata.SchemaCase getSchemaCase();
}
