# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Github action job to test core java library features on
# downstream client libraries before they are released.
on:
  push:
    branches:
    - main
  pull_request:
name: ci
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17, 21]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - run: java -version
    - run: mvn -B -ntp test
      # TODO: remove in the target repo
      working-directory: google-cloud-bigtable-kafka-connect-sink
  units-java11:
    # Building using Java 21 and run the tests with Java 11 runtime
    name: "units (11)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
      - name: "Set jvm system property environment variable for surefire plugin (unit tests)"
        # Maven surefire plugin (unit tests) allows us to specify JVM to run the tests.
        # https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#jvm
        run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
        shell: bash
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - run: mvn -B -ntp test
        # TODO: remove in the target repo
        working-directory: google-cloud-bigtable-kafka-connect-sink
  integrations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - run: java -version
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: latest
        install_components: beta,bigtable
    - run: |
        set -euo pipefail
        gcloud beta emulators bigtable start --host-port=0.0.0.0:8086 &
        mvn -B -ntp verify -DskipUnitTests
      # TODO: remove in the target repo
      working-directory: google-cloud-bigtable-kafka-connect-sink
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - run: java -version
    - run: mvn -B -ntp package -Dmaven.test.skip
      # TODO: remove in the target repo
      working-directory: google-cloud-bigtable-kafka-connect-sink
  windows:
    runs-on: windows-latest
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - run: java -version
    - run: mvn -B -ntp test
      # TODO: remove in the target repo
      working-directory: google-cloud-bigtable-kafka-connect-sink
  javadoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - run: java -version
    # TODO: also run javadoc:test-javadoc?
    - run: mvn -B -ntp javadoc:javadoc
      # TODO: remove in the target repo
      working-directory: google-cloud-bigtable-kafka-connect-sink
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - run: java -version
    - run: mvn -B -ntp spotless:check
      # TODO: remove in the target repo
      working-directory: google-cloud-bigtable-kafka-connect-sink
